# WARNING - Generated by {fusen} from /dev/mrbma.Rmd: do not edit by hand

test_that("mr_bma works", {
  lipid_exposures <- TwoSampleMR::mv_extract_exposures(id_exposure = c("ieu-a-299", "ieu-a-300", "ieu-a-301", "ieu-a-302"))
  cad_outcome <- TwoSampleMR::extract_outcome_data(snps = lipid_exposures$SNP, outcomes = "ebi-a-GCST005195")
  lipids_cad_harmonized <- TwoSampleMR::mv_harmonise_data(lipid_exposures, cad_outcome)
  mrbma_res <- mr_bma(lipids_cad_harmonized)
  mrbma_res_no_outliers <- mr_bma(lipids_cad_harmonized, remove_outliers = FALSE)
  mrbma_res_no_influential <- mr_bma(lipids_cad_harmonized, remove_influential = FALSE)
  mrbma_res_nyholt <- mr_bma(lipids_cad_harmonized, calculate_p = TRUE, nrepeat = 100)
  mrbma_res_kmin <- mr_bma(lipids_cad_harmonized, kmin = 1, kmax = 2)
  expect_type(mrbma_res, "list")
  expect_type(mrbma_res_no_outliers, "list")
  expect_type(mrbma_res_no_influential, "list")
  expect_type(mrbma_res_nyholt, "list")
  expect_type(mrbma_res_kmin, "list")
})

test_that("mr_bma_make_input works", {
  lipid_exposures <- TwoSampleMR::mv_extract_exposures(id_exposure = c("ieu-a-299", "ieu-a-300"))
  cad_outcome <- TwoSampleMR::extract_outcome_data(snps = lipid_exposures$SNP, outcomes = "ebi-a-GCST005195")
  lipids_cad_harmonized <- TwoSampleMR::mv_harmonise_data(lipid_exposures, cad_outcome)
  mrbma_input <- mrbma_make_input(lipids_cad_harmonized)
  expect_type(mrbma_input, "list")
})



