# WARNING - Generated by {fusen} from /dev/mrbma.Rmd: do not edit by hand

test_that("mr_bma_make_input works", {
  lipid_exposures <- TwoSampleMR::mv_extract_exposures(id_exposure = c("ieu-a-299", "ieu-a-300"))
  cad_outcome <- TwoSampleMR::extract_outcome_data(snps = lipid_exposures$SNP, outcomes = "ebi-a-GCST005195")
  lipids_cad_harmonized <- TwoSampleMR::mv_harmonise_data(lipid_exposures, cad_outcome)
  mrbma_input <- mrbma_make_input(lipids_cad_harmonized)
  expect_type(mrbma_input, "list")
})
