# WARNING - Generated by {fusen} from /dev/mrbma.Rmd: do not edit by hand

#' Perform Mendelian Randomization Bayesian Model Averaging
#'
#' @description This function takes harmonized exposure/outcome data and runs Mendelian Randomization Bayesian Model Averaging to identify and prioritize relationships between the exposures and outcome.
#'
#' @param harmonized_data (list) Harmonized data of exposures/outcomes of interest, generated using [TwoSampleMR::mv_harmonise_data()]
#' @param kmin
#' @param kmax
#' @param prior_prob
#' @param prior_sigma
#' @param top
#' @param nrepeat (numeric) Number of permutations used when estimating Nyholt-corrected False Discovery Rate
#'
#' @export

#' @examples
#' lipid_exposures <- TwoSampleMR::mv_extract_exposures(id_exposure = c("ieu-a-299", "ieu-a-300", "ieu-a-302"))
#' cad_outcome <- TwoSampleMR::extract_outcome_data(snps = lipid_exposures$SNP, outcomes = "ebi-a-GCST005195")
#' lipids_cad_harmonized <- TwoSampleMR::mv_harmonise_data(lipid_exposures, cad_outcome)
mr_bma <- function(harmonized_data, kmin = 5, kmax = 5, prior_prob = 0.5, prior_sigma = 0.5, top = 10, nrepeat = 100000) {
  
  cli::cli_progress_step("Preparing input")
  input_df <- mrbma_make_input(harmonized_data)
  
  return(input_df)
}

mrbma_make_input <- function(harmonized_data) {
  
  # Check input
  checkmate::assert_list(harmonized_data)
  
  # Format input
  beta_df <- harmonized_data$exposure_beta %>%
    as_tibble(rownames = "SNP") %>%
    bind_cols(
      harmonized_data$outcome_beta %>%
        as_tibble() %>%
        rename(outcome = value)
    ) %>%
    rename_with(.cols = !contains("SNP"), ~ glue::glue("beta_{.}"))

  se_df <- harmonized_data$exposure_se %>%
    as_tibble(rownames = "SNP") %>%
    bind_cols(
      harmonized_data$outcome_se %>%
        as_tibble() %>%
        rename(outcome = value)
    ) %>%
    rename_with(.cols = !contains("SNP"), ~ glue::glue("se_{.}"))

  pval_df <- harmonized_data$exposure_pval %>%
    as_tibble(rownames = "SNP") %>%
    bind_cols(
      harmonized_data$outcome_pval %>%
        as_tibble() %>%
        rename(outcome = value)
    ) %>%
    rename_with(.cols = !contains("SNP"), ~ glue::glue("pval_{.}"))
  
  harmonized_df <- beta_df %>%
    left_join(se_df, by = c("SNP")) %>%
    left_join(pval_df, by = c("SNP"))
  
  return(harmonized_df)
}
