# WARNING - Generated by {fusen} from /dev/mrbma.Rmd: do not edit by hand

#' mrbma_make_input
#'
#' Internal function to turn result of [TwoSampleMR::mv_harmonise_data()] into `mvMRInput`
#'
#' @return
#'
#' @noRd
# internal function to prepare input
mrbma_make_input <- function(harmonized_data) {
  # Check input
  checkmate::assert_list(harmonized_data)

  # Format input
  beta_df <- harmonized_data$exposure_beta %>%
    as_tibble(rownames = "SNP") %>%
    bind_cols(
      harmonized_data$outcome_beta %>%
        as_tibble() %>%
        rename(outcome = value)
    ) %>%
    rename_with(.cols = !contains("SNP"), ~ glue::glue("beta_{.}"))

  se_df <- harmonized_data$exposure_se %>%
    as_tibble(rownames = "SNP") %>%
    bind_cols(
      harmonized_data$outcome_se %>%
        as_tibble() %>%
        rename(outcome = value)
    ) %>%
    rename_with(.cols = !contains("SNP"), ~ glue::glue("se_{.}"))

  pval_df <- harmonized_data$exposure_pval %>%
    as_tibble(rownames = "SNP") %>%
    bind_cols(
      harmonized_data$outcome_pval %>%
        as_tibble() %>%
        rename(outcome = value)
    ) %>%
    rename_with(.cols = !contains("SNP"), ~ glue::glue("pval_{.}"))

  harmonized_df <- beta_df %>%
    left_join(se_df, by = c("SNP")) %>%
    left_join(pval_df, by = c("SNP"))

  beta_x_ivw <- harmonized_data$exposure_beta / harmonized_data$outcome_se
  beta_y_ivw <- harmonized_data$outcome_beta / harmonized_data$outcome_se

  mvmr_input <- new("mvMRInput",
    betaX = as.matrix(beta_x_ivw),
    betaY = as.matrix(beta_y_ivw),
    snps = harmonized_df$SNP,
    exposure = harmonized_data$expname$id.exposure,
    outcome = harmonized_data$outname$id.outcome
  )

  return(
    list(
      "harmonized_df" = harmonized_df,
      "mvmr_input" = mvmr_input
    )
  )
}
